services:
  - type: web
    name: norinder-mudi-bot
    env: node
    region: singapore
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: node --expose-gc --max-old-space-size=384 dist/index.js --characters="characters/norinder.character.json"
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: SERVER_PORT
        value: 3001
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TWITTER_USERNAME
        sync: false
      - key: TWITTER_PASSWORD
        sync: false
      - key: TWITTER_EMAIL
        sync: false
      - key: POST_INTERVAL_MIN
        value: 6000
      - key: POST_INTERVAL_MAX
        value: 10000
      - key: NODE_OPTIONS
        value: --expose-gc --max-old-space-size=384
      - key: DEBUG
        value: "*"
    healthCheckPath: /health
    autoDeploy: true 